#!/usr/bin/env python

import argparse

import configparser

from ldcoolp.curation.api import figshare
from ldcoolp.curation.api import qualtrics
from ldcoolp.curation import depositor_name

# Read in default configuration file
config = configparser.ConfigParser()


if __name__ == '__main__':
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description='Command-line driver for LD-Cool-P curation list retrieval.')
    parser.add_argument('--config', required=True, help='path to configuration file')
    parser.add_argument('--article_id', required=True, help='Figshare article ID')

    args = parser.parse_args()

    config.read(args.config)

    api_token = config.get('global', 'api_token')
    fs_admin = figshare.FigshareInstituteAdmin(token=api_token)

    qualtrics_dataCenter = config.get('curation', 'qualtrics_dataCenter')
    qualtrics_token = config.get('curation', 'qualtrics_token')
    qualtrics_survey_id = config.get('curation', 'qualtrics_survey_id')
    q = qualtrics.Qualtrics(qualtrics_dataCenter, qualtrics_token, qualtrics_survey_id)

    dn = depositor_name.DepositorName(args.article_id, fs_admin)

    print("************************************")
    print("Retrieving Deposit Agreement URL ...")
    full_url = q.generate_url(dn.name_dict)
    print(full_url)

    print("Exit 0")
