#!/usr/bin/env python

from os.path import dirname, exists, join
from os import mkdir

import argparse
import configparser

from datetime import date

from ldcoolp.curation import main
from redata.commons import logger

# Version and branch info
from ldcoolp import __version__, CODE_NAME
from redata.commons.git_info import GitInfo
from ldcoolp import __file__ as library_path

today = date.today()

# Config loader
from ldcoolp.config import dict_load

library_root_path = dirname(dirname(library_path))  # Retrieve parent directory to ldcoolp


if __name__ == '__main__':
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description='Command-line driver for LD-Cool-P prerequisite set-up.')
    parser.add_argument('--config', required=True, help='path to configuration file')
    parser.add_argument('--article_id', required=True, help='Figshare article ID')
    parser.add_argument('--url_open', action='store_true', help='Whether to use urlopen')
    parser.add_argument('--browser', action='store_true', help='Whether to use urlopen')
    # parser.add_argument('--api_token', required=True, help='Figshare API token')
    args = parser.parse_args()

    if not exists(args.config):
        raise FileNotFoundError(f"WARNING!!! Config file not found: {args.config}")

    gi = GitInfo(library_root_path)

    banner_message = f"""
    This is the command-line tool that automates data retrieval, and curatorial review set-up. It:
    1. Perform folder management for each deposit
    2. Retrieves the dataset
    3. Download a copy of the curatorial review process
    4. Attempt to retrieve the Qualtrics deposit agreement or provide you with the link

    {CODE_NAME} branch: {gi.branch}
    {CODE_NAME} version: {__version__}
    {CODE_NAME} commit hash: {gi.short_commit}
    Created by Chun Ly
    Issues? Submit a GitHub ticket: https://github.com/ualibraries/LD_Cool_P/issues/new
    """
    print(banner_message)

    # Load configuration
    try:
        config_dict = dict_load(args.config)
    except configparser.ParsingError:
        exit()

    curation_dict = config_dict['curation']

    # Define logfile
    root_directory_main = curation_dict[curation_dict['log_parent_dir']]

    log_dir = join(root_directory_main, curation_dict['log_dir'])
    if not exists(log_dir):
        mkdir(log_dir)
    logfile_prefix = 'prereq_script'
    log = logger.log_setup(log_dir, logfile_prefix)
    log_filename = logger.get_log_file(log.handlers[-1])

    lc = logger.LogCommons(log, logfile_prefix, gi,
                           code_name=CODE_NAME, version=__version__)

    lc.script_start()

    # Retrieve username, hostname, IP
    lc.script_sys_info()

    # Separate comma-separated list of articles
    articles = args.article_id.split(',')
    num_articles = len(articles)

    log.info(f"Number of Deposits: {num_articles}")

    # Loop over each article
    count = 0
    for ii in range(len(articles)):
        log.info(f"Retrieving: {articles[ii]} ...")  # ... {ii+1} / {num_articles}")

        # Run pre-req steps
        main.workflow(articles[ii], url_open=args.url_open, browser=args.browser,
                      log=log, config_dict=config_dict)
        count += 1

        log.info(f"Completed: {articles[ii]} ...")
        log.info(f"Completed: {count} / {num_articles}")

    # Change permission to mode=666 (rw for all)
    lc.log_permission()

    lc.script_end()
